name: CD

on:
  push:
    paths:
    - 'doc/**'

jobs:
  gh-pages:
    name: GitHub Pages
    runs-on: ubuntu-16.04
    if: "!contains(github.event.head_commit.message, '[cd skip]')"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: cargo install mdbook --no-default-features --features output --vers "^0.4.7"
    - name: Build
      run: |
        pushd doc
        mdbook build
        popd
    - name: Deploy
      run: ./deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
